"""research graph actions and reflections

Revision ID: 0002_m2
Revises: 0001_m1
Create Date: 2026-10-02 22:39:48.481559

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_m2"
down_revision: Union[str, Sequence[str], None] = "0001_m1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_layouts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("scope_key", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "scope_key", name="uq_layout_scope"),
    )
    with op.batch_alter_table("graph_layouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_layouts_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "mutation_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("result_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "operation", "request_id", name="uq_mutation_request"),
    )
    with op.batch_alter_table("mutation_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mutation_requests_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "reflections",
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_at", sa.String(length=40), nullable=True),
        sa.Column("end_at", sa.String(length=40), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("materials", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("deleted_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint("kind IN ('attempt','period')", name="ck_reflection_kind"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reflections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reflections_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reflections_project_id"), ["project_id"], unique=False)

    op.create_table(
        "research_items",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("deleted_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint("kind IN ('question','finding','direction')", name="ck_item_kind"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_research_items_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_research_items_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "actions",
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("direction_id", sa.String(length=36), nullable=True),
        sa.Column("origin_reflection_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.String(length=40), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("deleted_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "status IN ('planned','in_progress','blocked','paused','completed','cancelled')",
            name="ck_action_status",
        ),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["research_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_reflection_id"],
            ["reflections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_actions_direction_id"), ["direction_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_actions_origin_reflection_id"), ["origin_reflection_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_actions_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_actions_project_id"), ["project_id"], unique=False)

    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=True),
        sa.Column("item_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "(record_id IS NOT NULL) != (item_id IS NOT NULL)", name="ck_node_target"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["research_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id"),
        sa.UniqueConstraint("record_id"),
    )
    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_nodes_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "action_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("action_id", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("record_revision_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_revision_id"],
            ["record_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", "record_id", name="uq_action_record"),
    )
    with op.batch_alter_table("action_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_records_action_id"), ["action_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_records_record_id"), ["record_id"], unique=False
        )

    op.create_table(
        "graph_relations",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("target_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("deleted_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "relation_type IN ('related','subquestion','derived_from','tests','supports','challenges','extends','reuses')",
            name="ck_relation_type",
        ),
        sa.CheckConstraint("source_id != target_id", name="ck_relation_self"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["graph_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["graph_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("graph_relations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_relations_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_graph_relations_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_graph_relations_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            "uq_question_parent",
            ["source_id"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL AND relation_type = 'subquestion'"),
        )
        batch_op.create_index(
            "uq_relation_live",
            ["source_id", "target_id", "relation_type"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    op.create_table(
        "evidence_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=True),
        sa.Column("relation_id", sa.String(length=36), nullable=True),
        sa.Column("record_revision_id", sa.String(length=36), nullable=False),
        sa.Column("source_version_id", sa.String(length=36), nullable=True),
        sa.Column("field_path", sa.String(length=100), nullable=False),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("end", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("stance", sa.String(length=20), nullable=False),
        sa.Column("reviewed_record_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(item_id IS NOT NULL) + (relation_id IS NOT NULL) = 1", name="ck_evidence_parent"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["research_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_revision_id"],
            ["record_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["relation_id"],
            ["graph_relations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_references", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_references_item_id"), ["item_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_references_relation_id"), ["relation_id"], unique=False
        )

    op.create_table(
        "m2_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=True),
        sa.Column("relation_id", sa.String(length=36), nullable=True),
        sa.Column("action_id", sa.String(length=36), nullable=True),
        sa.Column("reflection_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "(item_id IS NOT NULL) + (relation_id IS NOT NULL) + (action_id IS NOT NULL) + (reflection_id IS NOT NULL) = 1",
            name="ck_revision_parent",
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["research_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reflection_id"],
            ["reflections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["relation_id"],
            ["graph_relations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", "version", name="uq_action_revision"),
        sa.UniqueConstraint("item_id", "version", name="uq_item_revision"),
        sa.UniqueConstraint("reflection_id", "version", name="uq_reflection_revision"),
        sa.UniqueConstraint("relation_id", "version", name="uq_relation_revision"),
    )
    with op.batch_alter_table("m2_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_m2_revisions_action_id"), ["action_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_m2_revisions_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_m2_revisions_reflection_id"), ["reflection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_m2_revisions_relation_id"), ["relation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("m2_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_m2_revisions_relation_id"))
        batch_op.drop_index(batch_op.f("ix_m2_revisions_reflection_id"))
        batch_op.drop_index(batch_op.f("ix_m2_revisions_item_id"))
        batch_op.drop_index(batch_op.f("ix_m2_revisions_action_id"))

    op.drop_table("m2_revisions")
    with op.batch_alter_table("evidence_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_references_relation_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_references_item_id"))

    op.drop_table("evidence_references")
    with op.batch_alter_table("graph_relations", schema=None) as batch_op:
        batch_op.drop_index("uq_relation_live", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index(
            "uq_question_parent",
            sqlite_where=sa.text("deleted_at IS NULL AND relation_type = 'subquestion'"),
        )
        batch_op.drop_index(batch_op.f("ix_graph_relations_target_id"))
        batch_op.drop_index(batch_op.f("ix_graph_relations_source_id"))
        batch_op.drop_index(batch_op.f("ix_graph_relations_owner_id"))

    op.drop_table("graph_relations")
    with op.batch_alter_table("action_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_records_record_id"))
        batch_op.drop_index(batch_op.f("ix_action_records_action_id"))

    op.drop_table("action_records")
    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_nodes_owner_id"))

    op.drop_table("graph_nodes")
    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_actions_project_id"))
        batch_op.drop_index(batch_op.f("ix_actions_owner_id"))
        batch_op.drop_index(batch_op.f("ix_actions_origin_reflection_id"))
        batch_op.drop_index(batch_op.f("ix_actions_direction_id"))

    op.drop_table("actions")
    with op.batch_alter_table("research_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_items_project_id"))
        batch_op.drop_index(batch_op.f("ix_research_items_owner_id"))

    op.drop_table("research_items")
    with op.batch_alter_table("reflections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reflections_project_id"))
        batch_op.drop_index(batch_op.f("ix_reflections_owner_id"))

    op.drop_table("reflections")
    with op.batch_alter_table("mutation_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mutation_requests_owner_id"))

    op.drop_table("mutation_requests")
    with op.batch_alter_table("graph_layouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_layouts_owner_id"))

    op.drop_table("graph_layouts")
    # ### end Alembic commands ###
