"""AI configuration tasks and suggestions

Revision ID: 0003_m3
Revises: 0002_m2
Create Date: 2026-10-03 12:32:50.671442

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_m3"
down_revision: Union[str, Sequence[str], None] = "0002_m2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_configs",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("encrypted_key", sa.Text(), nullable=True),
        sa.Column("test_status", sa.String(length=30), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "ai_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("target_record_id", sa.String(length=36), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.String(length=40), nullable=True),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed','cancelled')",
            name="ck_ai_task_status",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["ai_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "request_id", name="uq_ai_request"),
    )
    with op.batch_alter_table("ai_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_tasks_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_tasks_status"), ["status"], unique=False)

    op.create_table(
        "ai_suggestions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("original", sa.JSON(), nullable=False),
        sa.Column("accepted", sa.JSON(), nullable=True),
        sa.Column("record_id", sa.String(length=36), nullable=True),
        sa.Column("record_revision_id", sa.String(length=36), nullable=True),
        sa.Column("relation_id", sa.String(length=36), nullable=True),
        sa.Column("relation_revision_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("decided_at", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','accepted','edited_accepted','rejected')",
            name="ck_ai_suggestion_status",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_revision_id"],
            ["record_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["relation_id"],
            ["graph_relations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["relation_revision_id"],
            ["m2_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ai_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_suggestions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_suggestions_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_suggestions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_suggestions_task_id"), ["task_id"], unique=False)

    op.create_table(
        "ai_task_inputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("object_key", sa.String(length=10), nullable=False),
        sa.Column("material_key", sa.String(length=10), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=True),
        sa.Column("record_revision_id", sa.String(length=36), nullable=True),
        sa.Column("item_id", sa.String(length=36), nullable=True),
        sa.Column("item_revision_id", sa.String(length=36), nullable=True),
        sa.Column("source_version_id", sa.String(length=36), nullable=True),
        sa.Column("field_path", sa.String(length=100), nullable=False),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("end", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(record_id IS NOT NULL AND record_revision_id IS NOT NULL AND item_id IS NULL AND item_revision_id IS NULL) OR (item_id IS NOT NULL AND item_revision_id IS NOT NULL AND record_id IS NULL AND record_revision_id IS NULL AND source_version_id IS NULL)",
            name="ck_ai_input_target",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["research_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_revision_id"],
            ["m2_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_revision_id"],
            ["record_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ai_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "material_key", name="uq_ai_material"),
    )
    with op.batch_alter_table("ai_task_inputs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_task_inputs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "ai_suggestion_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("suggestion_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=30), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["ai_suggestions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_suggestion_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_suggestion_events_suggestion_id"), ["suggestion_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_suggestion_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_suggestion_events_suggestion_id"))

    op.drop_table("ai_suggestion_events")
    with op.batch_alter_table("ai_task_inputs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_task_inputs_task_id"))

    op.drop_table("ai_task_inputs")
    with op.batch_alter_table("ai_suggestions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_suggestions_task_id"))
        batch_op.drop_index(batch_op.f("ix_ai_suggestions_status"))
        batch_op.drop_index(batch_op.f("ix_ai_suggestions_owner_id"))

    op.drop_table("ai_suggestions")
    with op.batch_alter_table("ai_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_ai_tasks_owner_id"))

    op.drop_table("ai_tasks")
    op.drop_table("ai_configs")
    # ### end Alembic commands ###
